### PR TITLE
Add partition type GUIDs

### PR DESCRIPTION
**Pull request by zfs2019**
## Summary
- Add partition type GUIDs from other ZFS platforms.
- Also, make some uppercase letters lowercase to make it more consistent.

## References
[`EFI_MIDNIGHTBSD_ZFS`](https://www.midnightbsd.org/cgi-bin/viewvc.cgi/src/stable/1.1/sys/sys/gpt.h?revision=12159&view=markup#l104)
[`EFI_LINUX_DATA`](https://lists.gnu.org/archive/html/bug-parted/2011-06/msg00026.html)

EDIT: After the initial PR, I noticed that `EFI_ILLUMOS_ZFS` duplicates `EFI_USR`, so I removed that. Sorry about it.

### CODE REVIEW

**Comment by yurikoles** [comment]
Hi @zfs2019,

Had you chanced to push it upstream, e.g. ZoL, O3X?

**Comment by zfs2019** [comment]
@yurikoles It is already on ZoL.

- [`EFI_MIDNIGHTBSD_ZFS`](https://github.com/zfsonlinux/zfs/blob/a8577bdb32e091645df901d8501e44ef50748389/include/sys/efi_partition.h#L227)
- [`EFI_LINUX_DATA`](https://github.com/zfsonlinux/zfs/blob/a8577bdb32e091645df901d8501e44ef50748389/include/sys/efi_partition.h#L173) (The name is different, though.)

But yes, the [O3X equivalent](https://github.com/openzfsonosx/zfs/blob/master/include/sys/efi_partition.h) doesn't have these.
I will make a PR to O3X if this PR has been merged.

**Comment by zfs2019** [comment]
@lundman I have a question.
Does O3X require a partition type GUID to be defined for a pool to be importable?

**Comment by lundman** [comment]
Generally, ZFS doesn't care about partition types. It reads the ZFS label on all devices it can find, to identify devices.  Types is more so the OS can say it is ZFS.

**Comment by zfs2019** [comment]
@lundman Thanks. So I don't have to make a PR to O3X :)

**Pull request merged**
