### PR TITLE
(GH-109) Add icons to executables. 

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
This adds icons to various executables. It uses the icon from OpenZFS, although this could be changed fairly easily in the future. 

From #109

### CODE REVIEW

**Comment by lundman** [comment]
Neat, the Installer icon works and looks good.  The diff makes me think the executables should have icons, like `zpool.exe` `zfs.exe` but they do not seem to work.

Also get error when starting installer, it can be ignored, but probably indicates a problem:

Screen Shot 2020-04-03 at 9 35 07 (2)

**Comment by TheCakeIsNaOH** [comment]
The icons on the individual `.exes` are working for me. They get added in the visual studio build, not by the inno compiler. They are working in the appveyor build, if you extract the installer the icons are there- 

https://ci.appveyor.com/api/buildjobs/0oqeuj0qorg2twf4/artifacts/OpenZFSOnWindows-release.exe
image

As for the warning when running the installer, I am not sure. What Inno setup version are you compiling with? You also could try running the installer from the appveyor build to see if it also shows the warning.

**Comment by lundman** [comment]
Yep, total pebkac on the exe icons.

The error at start goes away if I shrink the openzfs-small.bmp to 25% (30% is NG). But could be something with the inno version I have, I will try to update first.

**Comment by lundman** [comment]
Updating Inno seemed to have worked. Cheers.

**Pull request merged**
